### ISSUE TITLE
Value error in prototype_multidoc_summarization_evaluation

### ISSUE THREAD

**Issue by s-aparajita** [chrishokamp/dynamic-transformer-ensembles#2]
While running prototype_multidoc_summarization_evaluation, ran into value error:

ValueError                                Traceback (most recent call last)
<ipython-input-5-e099be0d9529> in <module>
      8 }
      9 
---> 10 cluster_summaries = summarize(evaluation_args)

<ipython-input-4-2b8f07a738e2> in summarize(args)
     25 
     26         component_states, ensemble_state = \
---> 27             decoding_utils.generate(component_states, decoding_hyperparams['max_length'],
     28                                     ensemble_state=ensemble_state)
     29 

~\dynamic-transformer-ensembles-master\transformer_decoding\decoding_utils.py in generate(component_states, timesteps, ensemble_state, timestep_mask)
     33 
     34             component_states, ensemble_state = \
---> 35                 decoding_utils.ensembled_beam_search_step(component_states, ensemble_state, step_mask=step_mask)
     36 
     37     return component_states, ensemble_state

~\anaconda3\lib\site-packages\torch\autograd\grad_mode.py in decorate_context(*args, **kwargs)
     25         def decorate_context(*args, **kwargs):
     26             with self.__class__():
---> 27                 return func(*args, **kwargs)
     28         return cast(F, decorate_context)
     29 

~\dynamic-transformer-ensembles-master\transformer_decoding\decoding_utils.py in ensembled_beam_search_step(component_states, ensemble_state, step_mask)
    443     for state in component_states:
    444 
--> 445         state['outputs'] = outputs_from_state(state)
    446         state['next_token_logits'] = state['outputs'][0][:, -1, :]  # (batch_size * num_beams, vocab_size)
    447 

~\dynamic-transformer-ensembles-master\transformer_decoding\decoding_utils.py in outputs_from_state(state)
    397         use_cache=True
    398     )
--> 399     outputs = state['model'](**model_inputs)  # (batch_size * num_beams, cur_len, vocab_size)
    400     return outputs
    401 

~\anaconda3\lib\site-packages\torch\nn\modules\module.py in _call_impl(self, *input, **kwargs)
    887             result = self._slow_forward(*input, **kwargs)
    888         else:
--> 889             result = self.forward(*input, **kwargs)
    890         for hook in itertools.chain(
    891                 _global_forward_hooks.values(),

~\anaconda3\lib\site-packages\transformers\models\bart\modeling_bart.py in forward(self, input_ids, attention_mask, decoder_input_ids, decoder_attention_mask, head_mask, decoder_head_mask, cross_attn_head_mask, encoder_outputs, past_key_values, inputs_embeds, decoder_inputs_embeds, labels, use_cache, output_attentions, output_hidden_states, return_dict)
   1282                 )
   1283 
-> 1284         outputs = self.model(
   1285             input_ids,
   1286             attention_mask=attention_mask,

~\anaconda3\lib\site-packages\torch\nn\modules\module.py in _call_impl(self, *input, **kwargs)
    887             result = self._slow_forward(*input, **kwargs)
    888         else:
--> 889             result = self.forward(*input, **kwargs)
    890         for hook in itertools.chain(
    891                 _global_forward_hooks.values(),

~\anaconda3\lib\site-packages\transformers\models\bart\modeling_bart.py in forward(self, input_ids, attention_mask, decoder_input_ids, decoder_attention_mask, head_mask, decoder_head_mask, cross_attn_head_mask, encoder_outputs, past_key_values, inputs_embeds, decoder_inputs_embeds, use_cache, output_attentions, output_hidden_states, return_dict)
   1155 
   1156         if encoder_outputs is None:
-> 1157             encoder_outputs = self.encoder(
   1158                 input_ids=input_ids,
   1159                 attention_mask=attention_mask,

~\anaconda3\lib\site-packages\torch\nn\modules\module.py in _call_impl(self, *input, **kwargs)
    887             result = self._slow_forward(*input, **kwargs)
    888         else:
--> 889             result = self.forward(*input, **kwargs)
    890         for hook in itertools.chain(
    891                 _global_forward_hooks.values(),

~\anaconda3\lib\site-packages\transformers\models\bart\modeling_bart.py in forward(self, input_ids, attention_mask, head_mask, inputs_embeds, output_attentions, output_hidden_states, return_dict)
    747             input_shape = inputs_embeds.size()[:-1]
    748         else:
--> 749             raise ValueError("You have to specify either input_ids or inputs_embeds")
    750 
    751         if inputs_embeds is None:

**ValueError: You have to specify either input_ids or inputs_embeds**

Please help...

**Comment by chrishokamp** [comment]
Thanks for reporting -- I'll try to have a look at this this week

**Comment by malte-b** [comment]
Hey I'm also getting the same error. Any updates @chrishokamp?

**Comment by chrishokamp** [comment]
hi @malte-b @s-aparajita apologies for very late circle back, I just pinned the requirements, on the off chance you are still interested feel free to reopen this issue and I will (actually) have another look :sweat_smile:
